#!/bin/perl
# Copyright (c) 2013, Michael Wallio
# All rights reserved.
# 
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions 
# are met:
#   - Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
#   - Redistributions in binary form must reproduce the above copyright
#     notice, this list of conditions and the following disclaimer in 
#     the documentation and/or other materials provided with the 
#     distribution.
#   - Neither the name of ScaryRawr nor the names of its 
#     contributors may be used to endorse or promote products derived 
#     from this software without specific prior written permission.
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS 
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT 
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS 
# FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL 
# ScaryRawr BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, 
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT 
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF 
# USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, 
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT 
# OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF 
# SUCH DAMAGE.

use strict;
use warnings;

use Env;
use File::Basename;
use FindBin '$Bin';
use Getopt::Long;

my $MAJOR = 0;
my $MINOR = 2;
my $PATCH = 0;

sub get_licenses
{
  my @licenses;
  my $license_dir = "$Bin/license_files";
  opendir(my $dh, $license_dir) or die $!;

  while (my $file = readdir($dh)) {
    next unless (-f "$license_dir/$file" and $file =~ m/\.lic$/);
    $file =~ s/\.[^.]+$//;
    push(@licenses, $file);
  }

  closedir($dh);

  return @licenses;
}

sub print_version
{
  my $file_name = basename($0);
  print "$file_name $MAJOR.$MINOR.$PATCH\n";
  print "Written by Michael Wallio.\n\n";
  print "Copyright (c) 2013 ScaryRawr.\n";
  print "This is free software; see the source for license. There is NO ";
  print "\nwarranty; not even for MERCHANTABILITY or FITNESS FOR A \n";
  print "PARTICULAR PURPOSE.\n";
  exit 0;
}

sub print_help
{
  my $file_name = basename($0);
  print "Usage: $file_name [OPTIONS]...\n";
  print " -f, --file <file>        specify the output file(s)\n";
  print " -l, --license <license>  specify the license to use\n";
  print " -n, --name <name>        specify the author's name\n";
  print " -o, --org <organization> specify the organization\n";
  print " -h, --help               display this help and exit\n";
  print " -b, --version            output version information and exit\n";
  exit 0;
}

sub print_licenses
{
  print "Available Licenses:\n";
  print "  $_\n" foreach (@_);
  exit 0;
}

sub contains
{
  my ($listref, $find) = @_;
  my @list = @$listref;
  my %is_list = ();
  $is_list{$_} = 1 foreach (@list);
  return $is_list{$find};
}

my @files = ();
my @licenses = get_licenses();
my $get_version = '';
my $get_help = '';
my $license = '';
my $name = $USERNAME;
my $organization = $name;

GetOptions ('version' => \$get_version, 
            'help' => \$get_help,
            'license=s' => \$license,
            'name=s' => \$name,
            'organization=s' => \$organization,
            'file=s{,}' => \@files);


print_version() if ($get_version);

print_help() if ($get_help);

print_licenses(@licenses) unless (contains(\@licenses, $license));

